import { TreeNode } from './types';

export const initialData: TreeNode[] = [
  {
    id: "root",
    label: "Power Group 1",
    icon: "group",
    type: "group",
    expanded: true,
    parameters: {
      projectTitle: "Industrial 2-Axis Motion System",
      projectAuthor: "Lead Motion Engineer",
      projectCompany: "Advanced Automation Technologies",
      projectDate: new Date().toISOString().split('T')[0],
      projectNotes: "Master-Slave Cartesian Synchronization.\nAxis 1 operates as linear pick-and-place conveyor.\nAxis 2 operates as rotary indexing table.",
      cycleTime: 8,
      configuration: "Multi-Axis",
      supplyVoltage: 400,
      supplyPhase: 3,
      nominalBusVoltage: 540,
      infeedPeakPower: 12.5,
      targetBusVoltage: 560
    },
    children: [
      { 
        id: "axis_1", 
        label: "Axis 1 (Feed Conveyor)", 
        icon: "axis",
        type: "axis",
        expanded: true,
        parameters: {
          axisName: "Axis 1 (Feed Conveyor)",
          axisUsage: "Linear",
          feedConstant: 100, // 100 mm per rev
          profileType: "Time Based",
          mechanismType: "Belt",
          driverDiameter: 31.83, // mm (pi * D = 100mm)
          massLoad: 35.0,
          beltMass: 2.5,
          frictionCoeff: 0.12,
          inclineAngle: 0,
          gearboxVendor: "Wittenstein",
          gearboxModel: "LP+ 070 (i=5)",
          gearboxRatio: 5,
          gearboxEfficiency: 97,
          gearboxInertia: 0.28,
          gearboxBacklash: 8,
          gearboxMaxInputSpeed: 6000,
          gearboxNominalTorque: 45,
          gearboxMaxTorque: 72,
          gearboxMaxRadialForce: 1650,
          gearboxMaxAxialForce: 2100,
          gearboxTorsionalRigidity: 6.5,
          gearboxOutputShaftDiameter: 16,
          gearboxMass: 1.8,
          motorVendor: "Siemens",
          motorModel: "1FK7060-2AC71",
          ratedSpeed: 3000,
          peakSpeed: 6000,
          ratedTorque: 6.0,
          peakTorque: 18.0,
          ratedPower: 1.88,
          ratedCurrent: 4.2,
          motorEfficiency: 93.0,
          powerFactor: 0.92,
          motorInertia: 3.4,
          motorMass: 6.8,
          flangeSize: 100,
          shaftDiameter: 19,
          shaftLength: 40,
          keyway: true,
          maxRadialForce: 750,
          maxAxialForce: 250,
          torqueConstant: 1.43,
          voltageConstant: 92.0,
          windingResistance: 1.62,
          windingInductance: 11.5,
          coolingType: "Natural",
          protectionClass: "IP65",
          hasBrakeOption: true,
          brakeTorque: 13.0,
          allowableInertiaRatio: 10,
          driveVendor: "Siemens",
          driveModel: "S120-Booksize-5A",
          driveSupplyVoltage: 400,
          driveMaxCurrent: 10.0,
          pwmFrequency: 8,
          driveNominalBusVoltage: 540,
          driveInternalBusCapacitance: 150,
          motionProfileData: JSON.stringify([
            { id: "1", type: "S-Curve", duration: 1.2, distance: 300, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "distance" },
            { id: "2", type: "Dwell/Traverse", duration: 0.8, distance: 0, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "duration" },
            { id: "3", type: "Trapezoid", duration: 1.2, distance: -300, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "distance" },
            { id: "4", type: "Dwell/Traverse", duration: 0.8, distance: 0, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "duration" }
          ])
        }
      },
      { 
        id: "axis_2", 
        label: "Axis 2 (Index Table)", 
        icon: "axis",
        type: "axis",
        expanded: true,
        parameters: {
          axisName: "Axis 2 (Index Table)",
          axisUsage: "Rotary",
          feedConstant: 360,
          cycleMin: 0,
          cycleMax: 360,
          profileType: "Time Based",
          mechanismType: "Rotation Table",
          rotatingInertia: 85.0,
          frictionCoeff: 0.08,
          gearboxVendor: "Neugart",
          gearboxModel: "PLE080 (i=10)",
          gearboxRatio: 10,
          gearboxEfficiency: 96,
          gearboxInertia: 0.42,
          gearboxBacklash: 8,
          gearboxMaxInputSpeed: 5000,
          gearboxNominalTorque: 60,
          gearboxMaxTorque: 96,
          gearboxMaxRadialForce: 2100,
          gearboxMaxAxialForce: 2750,
          gearboxTorsionalRigidity: 8.5,
          gearboxOutputShaftDiameter: 20,
          gearboxMass: 2.4,
          motorVendor: "Siemens",
          motorModel: "1FK7080-2AF71",
          ratedSpeed: 3000,
          peakSpeed: 6000,
          ratedTorque: 12.0,
          peakTorque: 36.0,
          ratedPower: 3.5,
          ratedCurrent: 7.8,
          motorEfficiency: 94.5,
          powerFactor: 0.94,
          motorInertia: 6.2,
          motorMass: 12.5,
          flangeSize: 130,
          shaftDiameter: 24,
          shaftLength: 50,
          keyway: true,
          maxRadialForce: 1100,
          maxAxialForce: 380,
          torqueConstant: 1.57,
          voltageConstant: 101.0,
          windingResistance: 0.65,
          windingInductance: 6.2,
          coolingType: "Natural",
          protectionClass: "IP65",
          hasBrakeOption: true,
          brakeTorque: 22.0,
          allowableInertiaRatio: 8,
          driveVendor: "Siemens",
          driveModel: "S120-Booksize-9A",
          driveSupplyVoltage: 400,
          driveMaxCurrent: 18.0,
          pwmFrequency: 8,
          driveNominalBusVoltage: 540,
          driveInternalBusCapacitance: 220,
          motionProfileData: JSON.stringify([
            { id: "1", type: "S-Curve", duration: 0.8, distance: 90, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "distance" },
            { id: "2", type: "Dwell/Traverse", duration: 1.2, distance: 0, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "duration" },
            { id: "3", type: "S-Curve", duration: 0.8, distance: 90, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "distance" },
            { id: "4", type: "Dwell/Traverse", duration: 1.2, distance: 0, velocity: 0, accel: 0, decel: 0, jerk: 0, payload: 0, calcTarget: "duration" }
          ])
        }
      }
    ]
  }
];
